DeviceOrientationEvent: Define absolute's value on error
w3c/deviceorientation pull request #139
Opened 2024-02-13 12:30 UTC by rakuco

We were only requiring alpha, beta, and gamma to be null. It makes sense to
also require implementations to set absolute to the same value as well.

At the time of writing, this is done for completeness' sake though:
- Blink implements this behavior and sets absolute to false when a
  deviceorientation cannot be provided, and to true for
  deviceorientationabsolute events.
- Gecko does not send any events if it cannot provide readings (e.g. when
  there are no sensors available).
- WebKit only ships an iOS implementation, whose IDL does not even have an
  absolute attribute.

Fixes #119.

2024-02-13 12:58 UTC, rakuco commented
Accompanying web test in https://github.com/web-platform-tests/wpt/pull/44557

2024-02-13 23:29 UTC, reillyeon requested changes

2024-02-13 23:29 UTC, reillyeon commented on index.bs
> +If an implementation can never provide orientation information, the event should be fired with the {{DeviceOrientationEvent/alpha}}, {{DeviceOrientationEvent/beta}} and {{DeviceOrientationEvent/gamma
```suggestion
If an implementation can never provide orientation information, the event should be fired with the {{DeviceOrientationEvent/alpha}}, {{DeviceOrientationEvent/beta}} and {{DeviceOrientationEvent/gamma}} attributes set to null, and the {{DeviceOrientationEvent/absolute}} set to false.
```

2024-02-13 23:29 UTC, reillyeon commented on index.bs
> +If an implementation can never provide absolute orientation information, the event should be fired with the {{DeviceOrientationEvent/alpha}}, {{DeviceOrientationEvent/beta}} and {{DeviceOrientationEv
```suggestion
If an implementation can never provide absolute orientation information, the event should be fired with the {{DeviceOrientationEvent/alpha}}, {{DeviceOrientationEvent/beta}} and {{DeviceOrientationEvent/gamma}} attributes set to null, and the {{DeviceOrientationEvent/absolute}} set to true.
```

2024-02-14 08:02 UTC, rakuco commented on index.bs
> +If an implementation can never provide orientation information, the event should be fired with the {{DeviceOrientationEvent/alpha}}, {{DeviceOrientationEvent/beta}} and {{DeviceOrientationEvent/gamma
Oops, fixed. I've also added a missing "attribute" after "absolute".

2024-02-14 17:05 UTC, reillyeon approved these changes

2024-02-14 17:12 UTC, merged