Editorial: automatically generate the conformance section
w3c/deviceorientation pull request #155
Opened 2024-05-02 01:26 UTC by marcoscaceres

Drop redundant text and just let bikeshed generate the conformance section.

2024-05-02 07:20 UTC, rakuco requested changes
You need to remove `omit conformance` from the Bikeshed header, otherwise we'll end up with no conformance section at all.

2024-05-03 05:08 UTC, marcoscaceres commented
Thanks @rakuco. I'll fix "omit conformance" as part of this one.

2024-05-04 00:07 UTC, reillyeon approved these changes

2024-05-06 07:07 UTC, rakuco approved these changes

2024-05-07 04:10 UTC, merged