Editorial: use bikeshed shorthands for devicemotion firing steps
w3c/deviceorientation pull request #176
Opened 2024-05-08 01:32 UTC by marcoscaceres

2024-05-08 18:11 UTC, reillyeon requested changes

2024-05-08 18:11 UTC, reillyeon commented on index.bs
> +  1. [=list/For each=] |policy| of « "<a permission>"accelerometer"</a>", <a permission>"gyroscope"</a> »:
```suggestion
  1. [=list/For each=] |policy| of « <a permission>"accelerometer"</a>, <a permission>"gyroscope"</a> »:
```

2024-05-08 18:11 UTC, reillyeon commented on index.bs
> +        1. [=Fire an event=] named "devicemotion" at |window|, using {{DeviceMotionEvent}}, with the {{DeviceMotionEvent/acceleration}} attribute initialized to |acceleration|, the {{DeviceMotionEven
Link to #def-devicemotion?

2024-05-08 18:11 UTC, reillyeon commented on index.bs
> +      1. Set |rotationRate|'s <a for="DeviceMotionEventRotationRate">x axis rotation rate</a> to |platformRotationRate|'s value about the X axis, or null if it cannot be provided.
Use Bikeshed syntax for these references?

2024-05-14 05:11 UTC, marcoscaceres commented on index.bs
> +      1. Set |rotationRate|'s <a for="DeviceMotionEventRotationRate">x axis rotation rate</a> to |platformRotationRate|'s value about the X axis, or null if it cannot be provided.
```suggestion
      1. Set |rotationRate|'s [= DeviceMotionEventRotationRate/x axis rotation rate=] to |platformRotationRate|'s value about the X axis, or null if it cannot be provided.
```

2024-05-18 05:10 UTC, marcoscaceres commented
Should hopefully be good to go. Feel free to merge if it's all good @reillyeon 🙏

2024-05-21 00:42 UTC, reillyeon approved these changes

2024-05-21 00:42 UTC, reillyeon commented on index.bs
> +  1. If |topLevelTraversable|'s [=virtual sensor mapping=] [=map/contains=] "`linear`e>":
```suggestion
  1. If |topLevelTraversable|'s [=virtual sensor mapping=] [=map/contains=] "`linear-acceleration`":
```

2024-05-21 00:42 UTC, reillyeon commented on index.bs
> +      1. Let |virtualSensor| be |topLevelTraversable|'s [=virtual sensor mapping=]["`linear`e>"].
```suggestion
      1. Let |virtualSensor| be |topLevelTraversable|'s [=virtual sensor mapping=]["`linear-acceleration`"].
```

2024-05-21 00:46 UTC, merged