chore: Update README.md
w3c/deviceorientation pull request #178
Opened 2024-05-08 01:45 UTC by marcoscaceres

Update README to reflect joint deliverable status.

2024-05-08 18:15 UTC, reillyeon approved these changes

2024-05-08 19:30 UTC, anssiko requested changes
Some grammar nits. I wish we had a readme template for spec repos to adopt.

2024-05-08 19:30 UTC, anssiko commented on README.md
> +This is the repository in which the W3C's [Device Orientation and Motion](https://www.w3.org/TR/orientation-event/) specification, which is jointly maintained [Device and Sensors Working Group](https
```suggestion
This is the repository in which the W3C's [Device Orientation and Motion](https://www.w3.org/TR/orientation-event/) specification is jointly maintained by the [Devices and Sensors Working Group](https://www.w3.org/groups/wg/das/) and the [Web Applications Working Group](https://www.w3.org/groups/wg/webapps/).
```

2024-05-09 15:06 UTC, marcoscaceres commented
@anssiko see the Geolocation one. I think it’s quite good, as it gives a good overview of the API and purpose. We could do something like that here as a follow up.

2024-05-13 11:34 UTC, anssiko commented
Geolocation API readme examples are great and could be contributed to MDN developer docs when appropriate to reach more web developers.

I was thinking of a minimal baseline spec repo readme with information on how to contribute, how to build. Something that first into one page. I'm fine with repos having custom readmes, it gives them character.

2024-05-13 11:34 UTC, anssiko approved these changes

2024-05-14 05:02 UTC, merged

2024-05-14 05:09 UTC, marcoscaceres commented
> Geolocation API readme examples are great and could be contributed to MDN developer docs when appropriate to reach more web developers.

MDN has a really good [guide](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API/Using_the_Geolocation_API)

I guess if anything, we should probably remove the examples from the Geo README and point people to that 😅 (and maybe we could modernize what's on MDN).

> I was thinking of a minimal baseline spec repo readme with information on how to contribute, how to build. Something that first into one page. I'm fine with repos having custom readmes, it gives them character.

I still think that's better handled by the CONTRIBUTING.md ... For instance, the one for Web Manifest contains how to build instructions, style guide, etc. 

I personally prefer keep the READMEs minimal and without any duplicative information.... more like, if you want to contribute, read CONTRIBUTE.md, if you want to do Y, read Y.MD... and so on.