switch echidna from WD to CRD
w3c/deviceorientation pull request #189
Opened 2024-11-29 06:53 UTC by himorin

for post CRS publication

2024-12-03 20:42 UTC, anssiko requested changes

2024-12-03 20:42 UTC, anssiko commented on .github/workflows/auto-publish.yml
@himorin Bikeshed now requires Python 3.9+ that comes with `ubuntu-latest`. I believe that should fix this workflow.

2025-02-11 23:02 UTC, marcoscaceres approved these changes

2025-02-11 23:06 UTC, marcoscaceres commented
The error a markup error.

2025-02-11 23:07 UTC, marcoscaceres commented
I'm going to merge this and we can deal with the markup issue separately.

2025-02-11 23:07 UTC, merged