DeviceMotionEvent: Add a note about acceleration properties.
w3c/deviceorientation pull request #97
Opened 2021-07-08 12:58 UTC by rakuco

See #96 for an example of how these attributes can be confusing, especially
given accelerationIncludingGravity's name.

Add a note with a reference to what exactly that property measures, and
refence the Motion Sensors Explainer. It contains a more detailed
explanation about Accelerometer and LinearAccelerationSensor, which is
exactly the difference between the accelerationIncludingGravity and
acceleration attributes.

2021-07-08 12:58 UTC, rakuco commented
cc @reillyeon

2021-07-09 00:32 UTC, reillyeon requested changes

2021-07-09 00:32 UTC, reillyeon commented on index.bs
> +<p class=note>Note: in practice, {{DeviceMotionEvent/accelerationIncludingGravity}} represents the raw readings obtained from an accelerometer, or the [[G-FORCE]]. Also see [[MOTION-SENSORS]]: {{Devi
```suggestion
<p class=note>Note: in practice, {{DeviceMotionEvent/accelerationIncludingGravity}} represents the raw readings obtained from an [[MOTION-SENSORS#accelerometer]], or the [[G-FORCE]] while {{DeviceMotionEvent/acceleration}} provides the readings of a [[MOTION-SENSORS#linear-acceleration-sensor]] and is likely a sensor fusion.
```

2021-07-09 22:15 UTC, reillyeon approved these changes

2021-07-10 00:16 UTC, rakuco commented
Hmm, I don't think I have write access to this repo, so someone needs to squash and merge this PR.

2021-07-10 00:52 UTC, merged